  apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${appName}-docker
    name: ${appName}-docker
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${appName}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      dockerfile: |-
        FROM wildfly
        COPY demo.war /opt/jboss/wildfly/standalone/deployments/
        
      binary:
        asFile: demo.war
      type: Docker
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: wildfly:latest
      type: Docker
    triggers: []
